# Funding — Rogue Development (Aris Hadisopiyan)
# https://docs.github.com/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository

github: [rogue-dev-studio]
custom: ['https://rogue-dev-studio.github.io/']
